packages:
  - name: absl-py
    version: 2.1.0
  - name: astunparse
    version: 1.6.3
  - name: blinker
    version: 1.8.2
  - name: certifi
    version: 2024.6.2
  - name: charset-normalizer
    version: 3.3.2
  - name: click
    version: 8.1.7
  - name: colorama
    version: 0.4.6
  - name: Flask
    version: 3.0.3
  - name: flatbuffers
    version: 24.3.25
  - name: gast
    version: 0.5.4
  - name: google-pasta
    version: 0.2.0
  - name: grpcio
    version: 1.64.1
  - name: h5py
    version: 3.11.0
  - name: idna
    version: 3.7
  - name: itsdangerous
    version: 2.2.0
  - name: Jinja2
    version: 3.1.4
  - name: joblib
    version: 1.4.2
  - name: keras
    version: 3.3.3
  - name: libclang
    version: 18.1.1
  - name: Markdown
    version: 3.6
  - name: markdown-it-py
    version: 3.0.0
  - name: MarkupSafe
    version: 2.1.5
  - name: mdurl
    version: 0.1.2
  - name: ml-dtypes
    version: 0.3.2
  - name: namex
    version: 0.0.8
  - name: numpy
    version: 1.26.4
  - name: opt-einsum
    version: 3.3.0
  - name: optree
    version: 0.11.0
  - name: packaging
    version: 24.0
  - name: pandas
    version: 2.2.2
  - name: pip
    version: 24.0
  - name: protobuf
    version: 4.25.3
  - name: Pygments
    version: 2.18.0
  - name: python-dateutil
    version: 2.9.0.post0
  - name: pytz
    version: 2024.1
  - name: requests
    version: 2.32.3
  - name: rich
    version: 13.7.1
  - name: scikit-learn
    version: 1.5.0
  - name: scipy
    version: 1.13.1
  - name: setuptools
    version: 70.0.0
  - name: six
    version: 1.16.0
  - name: tensorboard
    version: 2.16.2
  - name: tensorboard-data-server
    version: 0.7.2
  - name: tensorflow
    version: 2.16.1
  - name: tensorflow-intel
    version: 2.16.1
  - name: termcolor
    version: 2.4.0
  - name: threadpoolctl
    version: 3.5.0
  - name: typing_extensions
    version: 4.12.1
  - name: tzdata
    version: 2024.1
  - name: urllib3
    version: 2.2.1
  - name: Werkzeug
    version: 3.0.3
  - name: wheel
    version: 0.43.0
  - name: wrapt
    version: 1.16.0
